[package]
name = "clonomap"
version = "0.1.0"
edition = "2024"
description = "Scalable inference of clonal structure in large AIRR-seq clones"

[features]
default = []
plot = ["plotters"]

[dependencies]
clap = { version = "4", features = ["derive"] }
ndarray = "0.15"
linfa = "0.7"
linfa-reduction = "0.7"
plotters = { version = "0.3", features = ["bitmap_backend"], optional = true }
rayon = "1.11.0"
anyhow = "1.0.100"

